[DOWNGRADE] Icon got removed
```
> Task :app:compileProdReleaseKotlin FAILED

> Task :app:copyRoomSchemas NO-SOURCE
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/about/AboutAppScreen.kt:14:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/about/AboutAppScreen.kt:15:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/about/AboutAppScreen.kt:156:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/about/AppCreditsScreen.kt:16:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/about/AppCreditsScreen.kt:17:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/about/AppCreditsScreen.kt:124:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:27:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:28:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:29:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:30:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:31:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:41:50 Unresolved reference 'MenuAnchorType'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:427:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:614:31 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:692:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:753:33 Unresolved reference 'PrimaryEditable'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addalert/AddNewWeatherAlertScreen.kt:768:39 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addapikey/ByoApiKeyScreen.kt:13:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addapikey/ByoApiKeyScreen.kt:14:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addapikey/ByoApiKeyScreen.kt:15:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addapikey/ByoApiKeyScreen.kt:255:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/addapikey/ByoApiKeyScreen.kt:292:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/CurrentAlertListScreen.kt:31:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/CurrentAlertListScreen.kt:32:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/CurrentAlertListScreen.kt:33:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/CurrentAlertListScreen.kt:406:35 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/CurrentAlertListScreen.kt:566:27 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/CurrentAlertListScreen.kt:571:27 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:6:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:7:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:8:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:9:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:45:18 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:53:38 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:106:38 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:135:22 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:143:42 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/alertslist/MainMenuItems.kt:184:42 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/details/WeatherAlertDetails.kt:26:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/details/WeatherAlertDetails.kt:27:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/details/WeatherAlertDetails.kt:28:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/details/WeatherAlertDetails.kt:29:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/details/WeatherAlertDetails.kt:291:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/details/WeatherAlertDetails.kt:301:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/details/WeatherAlertDetails.kt:309:43 Unresolved reference 'Icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/settings/UserSettingsScreen.kt:19:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/settings/UserSettingsScreen.kt:20:34 Unresolved reference 'icons'.
e: file:///home/runner/work/android-weather-alert/android-weather-alert/app/src/main/java/dev/hossain/weatheralert/ui/settings/UserSettingsScreen.kt:201:43 Unresolved reference 'Icons'.
gradle/actions: Writing build results to /home/runner/work/_temp/.gradle-actions/build-results/__run_3-1764640359126.json

[Incubating] Problems report is available at: file:///home/runner/work/android-weather-alert/android-weather-alert/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.14.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
209 actionable tasks: 186 executed, 23 from cache

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProdReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2m 58s

```